services:
  postgres:
    image: postgres:16
    container_name: sinapsis_db
    environment:
      POSTGRES_USER: sinapsis
      POSTGRES_PASSWORD: sinapsis123
      POSTGRES_DB: sinapsis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: